#!/usr/bin/env bash

CWD=$(pwd)
NEAREST_GIT_DIR=$CWD

while ! ((test -d "$NEAREST_GIT_DIR/.git") || [ "$NEAREST_GIT_DIR" = "/" ])
do
  NEAREST_GIT_DIR=$(dirname $NEAREST_GIT_DIR)
done

if [ "$NEAREST_GIT_DIR" = "/" ]
then
  NEAREST_GIT_DIR=$CWD
fi

LEN_NEAREST_GIT_DIR=${#NEAREST_GIT_DIR}
SUFFIX_AFTER_NEAREST_GIT_DIR=${CWD:$LEN_NEAREST_GIT_DIR}
DOCKER_WORKDIR=/home/$(whoami)/project$SUFFIX_AFTER_NEAREST_GIT_DIR

docker run \
  --interactive \
  --tty \
  --rm \
  --pull never \
  --user $(whoami) \
  --mount type=bind,readonly=false,source=$NEAREST_GIT_DIR,destination=/home/$(whoami)/project \
  --mount type=bind,readonly=false,source=/home/$(whoami)/.gitconfig,destination=/home/$(whoami)/.gitconfig \
  --workdir $DOCKER_WORKDIR \
  git scalar "$@"
